### ISSUE TITLE
How does install prerelase work?

### ISSUE THREAD

**Issue by niksy** [braver/Sass#94]
I’ve followed instructions in README but I still only get version `2.5.4` to install. Is there something else that needs to be done to have version `3.0.0` installed?

**Comment by the-ge** [comment]
Same here. Sublime Text Build 4126 on Kubuntu 21.10.
Installing from GitHub like in [this StackOverflow answer](https://stackoverflow.com/questions/23026201/sublime-text-3-how-to-install-plugins-from-github#answer-44441455) works.

**Comment by mikevaux** [comment]
I have also found that the prerelease install as described in the readme is not working, on Sublime Text Stable 4126.

I have added `"Sass"` to my prereleases key, like this

```json
"install_prereleases": [
	"Sass"
],
```

and have run `Package Control: Upgrade Package`, but the response I get from Package Control is: "There are no packages ready for upgrade".

I will have a go at installing manually as per @the-ge 's comment

**Comment by mikevaux** [comment]
@the-ge How did you get this to work? As per the answer you have linked to, I have added:

```
"repositories":
[
	"https://github.com/braver/SublimeSass"
],
```

to my package control settings, and have even uninstalled and reinstalled Sass, but am still stuck on `v2.5.4`.

My assumption here is that the package control settings repositories array should be checked first when Package Control checks for upgrades, and since that one has a 3.0 tag, I don't quite understand why it's not being found.. Maybe I'm misunderstanding something!

**Comment by mikevaux** [comment]
Oh, sorry, I think I've got it - it adds it as a whole separate package to the available packages rather than replacing the package control repository version, and it's actually called `SublimeSass` for this repository, rather than `Sass`.. 

Looks like you just get the latest `master` version though, rather than a tagged release, but that's probably not a bit problem 👍
